version = 1

[[analyzers]]
name = "csharp"
enabled = true

exclude_patterns = [
  "bin/",
  "obj/",
  "/*.Designer.cs",
  "/.g.cs",
  "**/.g.i.cs",
  "/Migrations/"
]

test_patterns = [
  "tests//*.cs",
  "/*.Tests.cs",
  "**/*Tests.cs"
]

[[transformers]]
name = "dotnet-test"
enabled = true
